apiVersion: v1
kind: Service
metadata:
  name: polarity-server
  namespace: {{ .Values.namespace }}
  labels:
    component: polarity
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    app: polarity-server
