apiVersion: v1
kind: Service
metadata:
  name: polarity-web
  namespace: {{ .Values.namespace }}
  labels:
    component: polarity
spec:
  {{- if .Values.istioEnabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
  selector:
    app: polarity-web
