apiVersion: v1
kind: Service
metadata:
  name: polarity-db
  namespace: polarity
  labels:
    app: polarityDb
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: {{ .Values.polarityDb.port }}
      targetPort: tcp-postgresql
  selector:
    app: polarityDb
---
apiVersion: v1
kind: Service
metadata:
  name: polarity-db-headless
  namespace: polarity
  labels:
    app: polarityDb
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: {{ .Values.polarityDb.port }}
      targetPort: tcp-postgresql
  selector:
    app: polarityDb
