{{- if .Values.polarityServer.licensePath }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.polarityServer.licenseSecret }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  polarity.lic: |
{{ .Files.Get .Values.polarityServer.licensePath | indent 4 }}
{{- end}}