apiVersion: v1
kind: Secret
metadata:
  name: polarity-server-lic
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  polarity.lic: |
{{ .Files.Get .Values.polarityServer.licensePath | indent 4 }}