{{- if .Values.istioEnabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: polarity
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "{{ include "polarity.fullname" . }}.{{ .Values.domain }}"
  gateways:
    - istio-system/dataplane
  http:
    - route:
        - destination:
            host: polarity-web
            port:
              number: 443
{{- end}}