apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: polarity
  namespace: polarity
spec:
  interval: 1m
  url: https://github.com/naps-dev/polarity.git
  ref:
    branch: "###ZARF_VAR_BRANCH###"
